apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  type: ClusterIP
  ports:
    - port: 8096
      targetPort: jellyfin
  selector:
    app: jellyfin
    part-of: jellyfin
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-internal
  annotations:
    metallb.universe.tf/allow-shared-ip: "jellyfin"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.61
  selector:
    app: jellyfin
    part-of: jellyfin
  ports:
    - name: jellyfin
      port: 8096
      targetPort: jellyfin
      protocol: TCP
  allocateLoadBalancerNodePorts: false
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-dlna
  annotations:
    metallb.universe.tf/allow-shared-ip: "jellyfin"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.61
  selector:
    app: jellyfin
    part-of: jellyfin
  ports:
    - name: dlna-service
      port: 1900
      targetPort: dlna-service
      protocol: UDP
    - name: dlna-client
      port: 7359
      protocol: UDP
      targetPort: dlna-client
  allocateLoadBalancerNodePorts: false
