apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  type: ClusterIP
  ports:
    - port: 8096
      targetPort: jellyfin
  selector:
    app: jellyfin
    part-of: jellyfin
---
kind: Service
apiVersion: v1
metadata:
  name: sonarr
spec:
  type: ExternalName
  externalName: sonarr.sonarr.svc.cluster.local
  ports:
  - port: 8989
    targetPort: 8989
---
kind: Service
apiVersion: v1
metadata:
  name: radarr
spec:
  type: ExternalName
  externalName: radarr.radarr.svc.cluster.local
  ports:
  - port: 7878
    targetPort: 7878
