kind: Deployment
apiVersion: apps/v1
metadata:
  name: jellyfin
  labels:
    app: jellyfin
    part-of: jellyfin
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
      part-of: jellyfin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jellyfin
        part-of: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: ghcr.io/linuxserver/jellyfin:latest
        ports:
        - name: jellyfin
          containerPort: 8096
        resources:
          limits:
            gpu.intel.com/i915: 1
            memory: 512Mi
          requests:
            memory: 256Mi
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Paris"
        readinessProbe:
          tcpSocket:
            port: jellyfin
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: jellyfin
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: jellyfin
          mountPath: /config
        - name: movies
          mountPath: /data/movies
        - name: series
          mountPath: /data/series
        - name: animes
          mountPath: /data/animes
        - name: musics
          mountPath: /data/musics
      volumes:
      - name: jellyfin
        persistentVolumeClaim:
          claimName: jellyfin
      - name: movies
        persistentVolumeClaim:
          claimName: movies
      - name: series
        persistentVolumeClaim:
          claimName: series
      - name: animes
        persistentVolumeClaim:
          claimName: animes
      - name: musics
        persistentVolumeClaim:
          claimName: musics
