kind: Deployment
apiVersion: apps/v1
metadata:
  name: jellyfin
  labels:
    app: jellyfin
    part-of: jellyfin
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@hourly"
    keel.sh/match-tag: true
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
      part-of: jellyfin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jellyfin
        part-of: jellyfin
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd
      containers:
      - name: jellyfin
        image: lscr.io/linuxserver/jellyfin:latest
        ports:
        - name: jellyfin
          containerPort: 8096
        resources:
          limits:
            gpu.intel.com/i915: 1
            memory: 700Mi
          requests:
            memory: 600Mi
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Paris"
        readinessProbe:
          httpGet:
            path: /health
            port: jellyfin
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: jellyfin
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: jellyfin
          mountPath: /config
        - name: movies
          mountPath: /data/movies
        - name: series
          mountPath: /data/series
        - name: animes
          mountPath: /data/animes
        - name: musics
          mountPath: /data/musics
        - name: books
          mountPath: /data/books
      volumes:
      - name: jellyfin
        persistentVolumeClaim:
          claimName: jellyfin
      - name: movies
        persistentVolumeClaim:
          claimName: movies
      - name: series
        persistentVolumeClaim:
          claimName: series
      - name: animes
        persistentVolumeClaim:
          claimName: animes
      - name: musics
        persistentVolumeClaim:
          claimName: musics
      - name: books
        persistentVolumeClaim:
          claimName: books
